### ISSUE TITLE
tslib dependency

### ISSUE THREAD

**Issue by minuz** [gund/ng-dynamic-component#115]
Hi @gund,
Quick question...
DO you actually use tslib in your library?? You added as dependency and I just noticed a warning about the missing dependency. However, even if I don't add the dependency, my app still works fine with your library version 2.0.3.

Is this really required?

**Comment by gund** [comment]
Hi, well when I compile the library it is done with `importHelpers` flag which means that the compiled code will create imports from `tslib`.

So I think that it is required. Maybe you had tslib installed by some other lib but otherwise you would get an error

**Comment by minuz** [comment]
No worries, I end up adding tslib to my project. Was just curious because I didn't really see the use on the code.
