### ISSUE TITLE
Rxjs 6 support

### ISSUE THREAD

**Issue by Gidmark** [gund/ng-dynamic-component#118]
Any plans on supporting Rxjs 6? Atm i get errors when it tries to include "rxjs/Subject" which should be "rxjs" and rxjs/add/operator/takeUntil which should be "rxjs/operators"

**Comment by gund** [comment]
Hi, yes, it is better to rely on lettable operators.

There is only one operator used (takeUntil) so it should be a pretty minor thing.
If you want, you are more than welcome to make a PR for it =)
