### ISSUE TITLE
Can't resolve './rxjs.imports'

### ISSUE THREAD

**Issue by bharatn** [gund/ng-dynamic-component#125]
Hello,

After I ran npm update(ng-dynamic-component 2.1.0 to 2.1.3) I am getting the following

I am getting webpack error when using ng-dynamic-component

ERROR in ./~/ng-dynamic-component/index.js
Module not found: Error: Can't resolve './rxjs.imports' in node_modules/ng-dynamic-component

@ ./~/ng-dynamic-component/index.js 5:0-24

Where is rxjs.imports located? I dont see it in the src tree

**Comment by bharatn** [comment]
I commented this line and able to use the ng-dynamic-component package without any issues so far so i am assuming its not used.

**Comment by gund** [comment]
The thing is I removed that file and import for it because I switched to lettable operators.

It's really weird why there is an import of this file at all in the compiled code...
