### ISSUE TITLE
Can't bind to 'ndcDynamicComponent' since it isn't a known property of 'ndc-dynamic'.

### ISSUE THREAD

**Issue by smohant2** [gund/ng-dynamic-component#134]
Hi,

I'm getting below mentioned error while using ndc-dynamic. I tried with <ng-container [ngComponentOutlet]="component"></ng-container>, which appears to be working fine. However in order to pass input data to component I need to use ndc-dynamic.

Attaching source code with error
[Dashboard.zip](https://github.com/gund/ng-dynamic-component/files/1944083/Dashboard.zip)

Please help!!!

compiler.js:485 Uncaught Error: Template parse errors:
Can't bind to 'ndcDynamicComponent' since it isn't a known property of 'ndc-dynamic'.
1. If 'ndc-dynamic' is an Angular component and it has 'ndcDynamicComponent' input, then verify that it is part of this module.
2. If 'ndc-dynamic' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (".layout}}">
                    <div class="card drop-shadow">
                        <ndc-dynamic [ERROR ->][ndcDynamicComponent]="dc.component"></ndc-dynamic>
                        <!-- <ng-container [ngCom"): ng:///AppModule/AppComponent.html@6:37
'ndc-dynamic' is not a known element:
1. If 'ndc-dynamic' is an Angular component, then verify that it is part of this module.
2. If 'ndc-dynamic' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("ol-xs-12 {{dc.layout}}">
                    <div class="card drop-shadow">
                        [ERROR ->]<ndc-dynamic [ndcDynamicComponent]="dc.component"></ndc-dynamic>
                        <!-- <ng-con"): ng:///AppModule/AppComponent.html@6:24

**Comment by gund** [comment]
1. You are missing to import module `DynamicModule` in your `AppModule` imports.
2. You can use `ndcDynamicInputs` even with `ngComponentOutlet`, however, again, you have to make sure step No.1 is fixed.

**Comment by smohant2** [comment]
Hi gund,

Thank you for your reply. Now I'm importing DynamicModule in app.module.ts, however I'm getting below mentioned error. Kindly let me know if you have any solution for this.

### Error
Uncaught Error: Unexpected value 'DynamicModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.js:485)
    at eval (compiler.js:15234)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15209)
    at JitCompiler._loadModules (compiler.js:34405)
    at JitCompiler._compileModuleAndComponents (compiler.js:34366)
    at JitCompiler.compileModuleAsync (compiler.js:34260)
    at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:239)
    at PlatformRef.bootstrapModule (core.js:5567)
    at eval (main.ts:11)

### app.module.ts

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
**import { DynamicModule,  } from 'ng-dynamic-component';**
import { AmChartsModule } from '@amcharts/amcharts3-angular';
import { NgComponentOutlet } from '@angular/common';
import { AppComponent } from './app.component';
import { HeaderComponent } from './header/header.component';
import { ChartComponent } from './chart/chart.component';
import { GridComponent } from './grid/grid.component';
import { MapComponent } from './map/map.component';
import { TakeInputComponent } from './take-input/take-input.component';

@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent,
    ChartComponent,
    GridComponent,
    MapComponent,
    TakeInputComponent
  ],
  imports: [
    **BrowserModule, AmChartsModule, DynamicModule**
  ],
  providers: [],
  entryComponents: [ChartComponent, GridComponent, MapComponent],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by BBlackwo** [comment]
@smohant2 you need to change it from `DynamicModule` to `DynamicModule.withComponents([])`. For example:

```js
imports: [
    DynamicModule.withComponents([MyDynamicComponent1, MyDynamicComponent2])
]
```

**Comment by astone2014** [comment]
I'm having this same issue with `ng-dynamic-component@7.0.2-no-barrels.2`.
I have `DynamicModule` in my `AppModule` imports.

`ndcDynamicInputs` and `ndcDynamicOutputs` works fine. but not `ndcDynamicAttributes`.

`error NG8002: Can't bind to 'ndcDynamicAttributes' since it isn't a known property of 'ndc-dynamic'.`

**Comment by gund** [comment]
For attributes to work you should import specific module `DynamicAttributesModule`.

It was changed since v7.
Please see chagelogs or readme for full list of changes.

**Comment by astone2014** [comment]
@gund you're the man. Thanks!
