### ISSUE TITLE
rxjs version bump to 6?

### ISSUE THREAD

**Issue by fijas** [gund/ng-dynamic-component#139]
Not able to update app to angular 6 as `ng-dynamic-component` depends on `^5.0.0` whereas angular 6 now depends on rxjs `^6.0.0`...

**Comment by p3root** [comment]
I would also need your module for angular 6 :)

**Comment by gund** [comment]
I think you can still safely update to v6 ignoring the npm warning. It's basically just a cosmetic thing in the package.json.

But yeah it's a good idea to update the version range =)

**Comment by gund** [comment]
Oh also all angular dependencies should be bumped to v6 range along with typescript version.

And that means that it should be published as a major release (as a breaking change).

**Comment by fijas** [comment]
Yes, you are right, it was just a warning that I was able to ignore. `ng update` was throwing out random errors which I thought was caused by this. In the end I had to update to version 6 manually. I used the instructions [found here](https://github.com/angular/angular-cli/issues/10621#issuecomment-386612334) for that.

Yeah this will definitely require a major version release as that also keeps in live with your versioning scheme of having a new major release corresponding with each Angular major release...

**Comment by snowyu** [comment]
Get rid of npm warning is simple: 

```js
  "peerDependencies": {
    "@angular/common": ">=5.0.0",
    "@angular/core": ">=5.0.0",
    "rxjs": ">=5.0.0",
    "tslib": ">=1.0.0"
  },
 
```

But you should read this first [RxJS v5.x to v6 Update Guide](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md)

**Change from**:
```ts
//rx5.x 
import { takeUntil } from 'rxjs/operators';
import { Subject } from 'rxjs/Subject';
```

**TO**: 
```ts
//rx6.x 
import { takeUntil } from 'rxjs';
import { Subject } from 'rxjs';
```

**Comment by snowyu** [comment]
Here are: [The Angular 6 Upgrade Guide](https://update.angular.io).

**Comment by gund** [comment]
@snowyu thanks for the link, however I don't think there is something related to this error...

I think it is only happening in unit test but will have to verify by running in ng6 test app to be sure.

**Comment by kamilkisiela** [comment]
Doing some work [here](https://github.com/gund/ng-dynamic-component/pull/141), feel free to help
