### ISSUE TITLE
'ndcDynamicComponent' error even if imported in app.module

### ISSUE THREAD

**Issue by dcp3450** [gund/ng-dynamic-component#142]
I'm getting the "Can't bind to 'ndcDynamicComponent' since it isn't a known property of 'ndc-dynamic'." error just like in #134 however I am importing per the readme:

app.module.ts:

```
...
//dynamic views
import { DynamicModule } from 'ng-dynamic-component';
import { TestViewComponent } from './views/test-view/test-view.component';

...
@NgModule({
  declarations: [
    ...,
    TestViewComponent
  ],
  imports: [
   ...,
    DynamicModule.withComponents([TestViewComponent])
  ],
  providers: [
	  ...
  ],
  bootstrap: [AppComponent]
})
```

grid.component.html:

```
<div id="grid">
    <gridster [options]="options">
    <gridster-item [item]="item" *ngFor="let item of dashboard;let i = index;">
      <div class="grid-header drag-handle">
        <span class="handle-icon"><i class="material-icons">open_with</i></span>
        <span class="close-icon" (click)="removePanel(item)"><i class="material-icons">close</i></span>
      </div>
      <ndc-dynamic [ndcDynamicComponent]="component"></ndc-dynamic>
    </gridster-item>
  </gridster>
</div>
```

grid.component.ts:

```
...
export class GridComponent implements OnInit {
  
  ...
  
  component = TestViewComponent;
...
}
```

I trying to test adding my test view in my grid items which will eventually be loaded dynamically based on options the user selects.

**Comment by dcp3450** [comment]
I had to import into my parent module. I assumed I had to import into the app module

**Comment by gund** [comment]
@dcp3450 so is it working now?

**Comment by dcp3450** [comment]
It's working when I also `import { TestViewComponent } from './views/test-view/test-view.component';` into the component that will set that dynamic component. However, this relates to my other issue #145

**Comment by gund** [comment]
okay let's then keep that issue alive
