### ISSUE TITLE
from a Dynamic loaded component how can change the value of another dynamic loaded component

### ISSUE THREAD

**Issue by vimalkovath** [gund/ng-dynamic-component#169]
```
<rio-hello name="World"></rio-hello> 
 <rio-hello [name]="helloName"></rio-hello>  
```

1.onClick of first component change the value of second coponent

2.Want to change the name from "helloworld" to "myworld". both in
same page same component loaded. how can i differentiate and change the value.

3. If both are loaded dynamically how i can access the instance and change value dynamically.

**Comment by gund** [comment]
Well you do this as you would do with 2 normal components: through the parent component.

Just listen on one component output and update input on other component.

**Comment by vimalkovath** [comment]
Thank you @gund  . i did thanks for your support . 
What i did is created a service to save all instance of components.
passed which componentID and get the instance and changed. 
i think this is what u told. 
If not If you have any other good ways please suggest that also. 

Thanks again.
