### ISSUE TITLE
How to unload and load different component

### ISSUE THREAD

**Issue by shan75** [gund/ng-dynamic-component#175]
Hi

Thanks for this library. This is a great piece of work which helps to load components dynamically.  I am struggling to achieve one thing.

I need to build a four step wizard in my app. I need to load one component to next component for four steps and also navigate between back and forth.  For example on page load I setup 
Wizard1Component dynamically which works. On click of of next button, I need to load Wizard2Component and it works.  But wizard two will have back and next buttons. I can't load wizard1Component again. It is not changing or not giving any errors. 

Is there any issues to achieve this?  Or how can I achieve this?

Please advice

Thanks
Shan

**Comment by gund** [comment]
Hi, to load/unload dynamic components you just have to change the `@Input` and that will be enough.
To unload - you can set it to `null`.

**Comment by semlibraries** [comment]
Hi @gund  I done it here: https://angular-zupxfn.stackblitz.io
Hope this shows. You can see in the console log.

**Comment by frontr-uk** [comment]
there is an issue trying to update the component on calling a method.

**Comment by CaptainMat** [comment]
Hello, is it possible to report this fix in V2.X ?
