### ISSUE TITLE
Cannot find Dynamic Module

### ISSUE THREAD

**Issue by dmanjava** [gund/ng-dynamic-component#21]
Hello,

 I used you angular 4 component and it works just fine with an angular 4 cli project .  But we have an angular cli 2 application and app,module.ts throws a compile time error  of 'cannot load module Dynamic Module'  I am using version ^0.0.1 as per your instructions. Please let me know how to get around this..

**Comment by gund** [comment]
That's weird, it was working fine with version 2...
Can you please provide plnkr?

**Comment by dmanjava** [comment]
You for your prompt response yes I will put one together today and send it
over to you.

**Comment by dmanjava** [comment]
I just upgraded to Angular 4 and it works so not working with Angular 2 problem.
