### ISSUE TITLE
Error when building prod version

### ISSUE THREAD

**Issue by pharindoko** [gund/ng-dynamic-component#214]
Hi,
Recognized first when building my application in travis ci
Issue does not occur using v 4.0.1 / 3.1.2 

Version: **4.0.2** used in Angular CLI Application 7.2.2 with @angular packages v. 7.2.0 / 7.2.1
Commands tested: 
FAIL - ng build ngx-chartboard-sample **--prod --aot**
FAIL - ng build ngx-chartboard-sample **--prod**
WORKS - ng build ngx-chartboard-sample

Error:

ERROR in ./src/app/ngx-chartboard-editor/modules/chartboard-dialog/step-add-component/step-add-component.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../../../../node_modules/ng-dynamic-component/ng-dynamic-component.ngfactory' in '/Users/uid10804/Documents/development2/ngx-chartboard/projects/ngx-chartboard-sample/src/app/ngx-chartboard-editor/modules/chartboard-dialog/step-add-component'

**Comment by gund** [comment]
Does this still occur?
