### ISSUE TITLE
How to access inputs in the dynamic component passed from the creating component

### ISSUE THREAD

**Issue by mcanfield** [gund/ng-dynamic-component#23]
Hiya! Quick questions, the documentation only shows how to set inputs/outputs, but not how to use them on the dynamically rendered component. For example given the following component:

```
@Component({
  selector: 'my-component',
  template: `<ndc-dynamic [ndcDynamicComponent]="component"
                          [ndcDynamicInputs]="inputs"
                          [ndcDynamicOutputs]="outputs"
                          ></ndc-dynamic>`
})
class MyComponent {
  component = MyDynamicComponent1;
  inputs = {
    hello: 'world',
    something: () => 'can be really complex'
  };
  outputs = {
    onSomething: (type) => alert(type)
  }
}
```

How would I access the input values from within `MyDynamicComponent1`? Or am I misunderstanding the purpose of the inputs/outputs?

```
@Component({
  selector: 'my-dynamic-component1',
  template: `<div>Hello, {{inputs.hello}}!</div>`
})
class MyDynamicComponent1 {
 // How can I get a hold of the inputs passed from "my-component"? For example, I'd like to access the "inputs.hello".
...
}
```

**Comment by gund** [comment]
Hi! Good question. I just thought it is obvious =)
It's actually standard angular @Inputs/@Outputs on the dynamic components.
This lib will make shure to bind them like the angular does and also trigger all relevant life cycle hooks.
So from dynamic component point of view you do not do anything special at all (no magic) =)

**Comment by mcanfield** [comment]
@gund thanks for the quick reply! So I now understand how the `inputs` work, but am still at a loss for grasping how `outputs` do? I'm used to those being event emitters, but the source code looks like it just subscribes to changes on something... I'm too unfamiliar with inner workings to grasp complete comprehension.

Could you modify this [http://plnkr.co/edit/wdYufHejtiDCMZldyKjc](http://plnkr.co/edit/wdYufHejtiDCMZldyKjc?open=app%2Fapp.component.ts&p=preview) to demonstrate `[ndcDynamicOutputs]` interaction between parent/child? I think a concrete example will make things abundantly clear. 

Also, thanks for make this library, it's helping solve a headache I was having 😃 !

**Comment by gund** [comment]
Sure, I have made change to plunkr here: http://plnkr.co/edit/DA5yPFVLNBq50ton4gk9

Basically your `@Outputs` are ordinary Event Emitters (`Observables`) and the lib will internally subscribe to them and dispatch events to the functions you provided in `[ndcDynamicOutputs]`.

**Comment by mcanfield** [comment]
Ah, great! The thought occurred to me late yesterday to assign actual `EventEmitter`, but I never got around to trying it that way. Very clear now. Thanks so much!

**Comment by gund** [comment]
No problem. I will consider adding an example to the docs =)
Cheers!
