### ISSUE TITLE
Update dependencies to Angular 8

### ISSUE THREAD

**Issue by patrickschroeter** [gund/ng-dynamic-component#257]
When using ng-dymaic-component with the latest Version of Angular you get an error while installing npm packages:

`ng-dynamic-component@4.0.2 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by gund** [comment]
Hi, I do not think this is an error but rather a warning from `npm`.


Probably you can ignore it and it still will work.

However I will actually update it to Angular 8 and PR is always welcome =)

**Comment by gund** [comment]
Released in [`v5.0.0`](https://github.com/gund/ng-dynamic-component/releases/tag/v5.0.0)
