### ISSUE TITLE
Dynamic directives do not work with AOT

### ISSUE THREAD

**Issue by cice** [gund/ng-dynamic-component#278]
Using dynamic directives in production/AOT-compiled code does not work. The reason is quite simple: the dynamic directive application needs the decorator metadata to work, but this is stripped away in AOT.
I don't know of any way to tell the compiler to keep the metadata (and doubt that it is desirable)? 
Anyway, i think this is a very fundamental restriction, and could may be mentioned in the documentation?
Cheers!

**Comment by gund** [comment]
Hi, thanks for reporting this issue.

You are right that reflect metadata is not available in production mode.

There might be possible case to resolve missing reflect metadata without relying on reflection - we can find out where Angular stores that data - and access that instead.

But I will have to check the format of that data before proceeding with new implementation.
Also if you want you can help with this and submit a PR =)

**Comment by cice** [comment]
I will check it out. Thx btw for that great package!

**Comment by nickbullock** [comment]
@gund  @cice maybe this option in tsconfig will help
```
"compilerOptions": {
    "emitDecoratorMetadata": true
}
```

**Comment by gund** [comment]
@nickbullock this information generated by Typescript is stripped by the angular compiler in AOT mode.

**Comment by gund** [comment]
I think this issue should be resolved in v7 of this library which is for Angular v10+ since I've updated a way how directive metadata is accessed.
Could you guys please try it to see if it's fixed on v7?

**Comment by chriswhite199** [comment]
Seems to work for me with 7.0.1, both via `ng serve --aot` and with `ng build --prod --aot --optimization`

**Comment by gund** [comment]
Thanks for the confirmation. I will close this issue.
Please open a new one if you have any problems with it.
