### ISSUE TITLE
Problem on setting inputs for a component duplication (same comp rendered more then one time)

### ISSUE THREAD

**Issue by cristreet** [gund/ng-dynamic-component#293]
In my case I have a list of components that I render using a *ngfor:

```
 ... *ngFor="let dashboardItem of dashboard ..."
    <ndc-dynamic 
          [ndcDynamicComponent]=components[dashboardItem.component.name]
          [ndcDynamicInputs]="dashboardItem.component">
     </ndc-dynamic>
```
where "components" is an array containing the components list to render.

My problem occur when in this comps list there are more then one the same component, in that case the inputs of the second component will overwrite the first componet inputs.

How can I do in order to have differents instances for each component?

**Comment by gund** [comment]
Hi, I'm not sure I fully understand your issue.

Would it be possible for you to create live example on stackblitz.com to show the problem?

**Comment by cristreet** [comment]
It was an error, in my code, about the inputs instance and not about the component. 
Thanks

**Comment by epoch79** [comment]
How did you pass the input from template. i have the same issue

**Comment by cristreet** [comment]
Just passing a new instance of the input item, in my example "dashboardItem". I am using the drang & drop for passing components to ndc-dynamic and during the drag start I am creating a new instance of that component.

**Comment by cristreet** [comment]
> How did you pass the input from template. i have the same issue

Just passing a new instance of the input item, in my example "dashboardItem". I am using the drang & drop for passing components to ndc-dynamic and during the drag start I am creating a new instance of that component.

**Comment by epoch79** [comment]
thank you..
