### ISSUE TITLE
Understanding withComponents

### ISSUE THREAD

**Issue by alastair-todd** [gund/ng-dynamic-component#328]
I am confused about the module imports for this library.

I have a generic data table in one Module which will do the dynamic loading of components declared in another module.

```
GenericDataTableModule (creates components dynamically via passed in column config)
SpecificDataTableModule
 - DynamicColumnComponent
```

How to I use `withComponents `in this scenario since `GenericDataTableModule `should have no knowledge of `SpecificDataTableModule` ?

Worth noting: `GenericDataTableModule  `and `SpecificDataTableModule` are in ng libraries, so where does `withComponents` go? `AppModule`?

Oh and `SpecificDataTableModule` is lazy-loaded!

**Comment by gund** [comment]
Hi, you do not need to provide components in AppModule imports if they are already provided in other module. Simply pass empty array to import function.

**Comment by kevinsuarez-recycob** [comment]
some example?

**Comment by gund** [comment]
As simple as:
```ts
@NgModule({
  imports: [DynamicModule.withComponents([])]
})
export class AppModule {}
```

**Comment by alastair-todd** [comment]
This wasn't necessary for me...the import in the library module was enough
