### ISSUE TITLE
Usage of local template variables in output callbacks (for example in *ngFor)

### ISSUE THREAD

**Issue by Platonn** [gund/ng-dynamic-component#331]
Sometimes it's important to access not only the argument `$event`, but also the local template variables in the output callback, i.e. the array element (or index) coming from `*ngFor`. I propose below some solution, but I'm curious if you have any better approach or suggestions:

We could define an object for `[outputs]` not in the component controller (TS), but in the template (HTML), inside `*ngFor` and use there `.bind` (i.e. `.bind(this, element, elementIndex)`). But I have the following concerns:
- memory: creating a fresh function on each change detection 👎 
- freezed order of arguments: the argument `$event` must be the last (as we can bind only local template variables, but the argument `$event` can be curried laizly only as the last one (when event occurs) . _It's an issue for library authors who sometimes need to add a new optional argument to an exising public method of a component and don't want to reorder method's arguments for backward compatibility_

Maybe you have any other concerns? Or suggestions?
Thanks in advance!

**Comment by gund** [comment]
Hi @Platonn,

Thanks for the idea - I think it makes sense.

What I have in mid is to create a helper pipe that will take a callback function and then any arguments will be memorised and combined with the `$event` variable.

It may look something like this:
```html
<dynamic-component
  *ngFor="let component in components; let i = index"
  [component]="component"
  [ndcDynamicOutputs]="{
    onEvent: eventCallback | ndcWithArgs: i
  }"
></dynamic-component>
```

What do you think about this use-case?

**Comment by Platonn** [comment]
Hi @gund, thanks. Pipe is a nice performance improvement, indeed. Personally I like it short `ndcArgs`.
For flexibility of the arguments' order, what do you think about a custom placeholder for `$event`, i.e. a global `ndcEvent` singleton object, i.e. `someFunc | ndcArgs : param1 : ndcEvent : param2`. The drawback is that this placeholder needs to be exposed by the TS controller class of the current component.

**Comment by gund** [comment]
I think that it's not a good idea to introduce some kind of a custom variable like `ndcEvent` for passing the `$event` argument to the event handler.

Rather we can just bind the template arguments first to the handler function and then make the `$event` argument always last by convention.
In this way we will not have to create extra stuff in templates and just assume that event is always the last argument in the handlers used with `ndcArgs` pipe.

**Comment by Platonn** [comment]
Totally agreed. 
A custom variable was proposed only as a backup solution to support an edge case: when you already have a method with the event as not-last arg _and_ you don't want to change the order of arguments (due to various reasons, i.e. you are library author who wants to avoid breaking changes). 

That being said, a custom pipe and custom variable handling such an edge cases can be implemented by the library authors themselves, if only they need it.

**Comment by gund** [comment]
Alright, so we can agree on creating `ndcArgs` pipe that will bind a function with template arguments and pass `$event` variable as a last argument.

I may work on this at some time later but if you have a time - PR is very welcome =)
