### ISSUE TITLE
What's the usecase of this and what does it solve what Angular doesn't already do?

### ISSUE THREAD

**Issue by ciesielskico** [gund/ng-dynamic-component#355]
Pretty much the title, I've taken over a project from someone and I don't see the benefit of using this library. Don't treat this as an insult but rather a question for an update for the readme.md to maybe add a sentence or two about what this library solves :)

**Comment by gund** [comment]
This pretty much explains main use-case: https://github.com/gund/ng-dynamic-component#inputs-and-outputs.
There are other things that this lib provides - but main focus is on complete inputs/outputs support

**Comment by ciesielskico** [comment]
Ok so to understand what this lib does over what Angular doesn't provide out of the box - in Angular we can use `ng-container` with `*ngComponentOutlet` but not pass `@Input` and `@Output` parameters, and this lib enables us to do exactly that?

**Comment by gund** [comment]
Yes, that is correct.

**Comment by ciesielskico** [comment]
Thanks
