### ISSUE TITLE
 An accessor cannot be declared in an ambient context - during compiling

### ISSUE THREAD

**Issue by guypeled1** [gund/ng-dynamic-component#360]
I get this error when compiling. 
how can I solve this?

**Comment by guypeled1** [comment]
node_modules/ng-dynamic-component/lib/component-injector/component-outlet-injector.directive.d.ts:6:9

**Comment by gund** [comment]
Can you pls specify during which compile phase is this happening: `ngcc` or `ngc` (when your app is compiled)?

**Comment by xVinCe** [comment]
@guypeled1 I had the same problem, was due to having the wrong version: If you are on Angular 8 you should have 5.x.x as mentioned here https://github.com/gund/ng-dynamic-component#ng-dynamic-component

**Comment by gund** [comment]
Closing this as it is solved. Please create new issue if you still have this error.
