### ISSUE TITLE
xi18n : Error with DynamicModule import

### ISSUE THREAD

**Issue by nlapointe-factory** [gund/ng-dynamic-component#368]
Hi,
The command `ng xi18n` generates error:

> ERROR in Unexpected value 'undefined' exported by the module 'DynamicModule in /path/to/node_modules/ng-dynamic-component/ng-dynamic-component.d.ts'

Just with an import in a module (ex.: in app.module.ts). I tried with DynamicComponentModule, same error (with 'DynamicComponentModule' in message)

Versions:
Angular: 9.1.0
Angular-cli: 9.1.0
ng-dynamic-component: 6.1.0

**Comment by gund** [comment]
This could be due to the barrel re-exports that exists also when building in some projects with ng-packagr (see #365)

Please give a try to the version without barrels (tag `@no-barrels` on NPM) and let me know if it fixes the issue.

**Comment by nlapointe-factory** [comment]
Hey gund, working great with no-barrels (this one: 6.1.1-no-barrels.1 )

Many thanks

**Comment by gund** [comment]
Awesome!

I will keep the fix in separate tag for now until the [bug upstream](https://github.com/angular/angular/issues/20931) is resolved.

And then, hopefully, there will be no need for this extra tag =)
