### ISSUE TITLE
[Bug] ERROR: Unexpected value 'undefined' imported by the module

### ISSUE THREAD

**Issue by gund** [gund/ng-dynamic-component#369]
You may or may not encounter this error during your library build or xi18n build.

Error will look like:
```
ERROR in Unexpected value 'undefined' exported by the module 'DynamicModule in ...

or

ERROR: Unexpected value 'undefined' imported by the module 'DynamicComponentModule in ...
```

Regardles of the module - the reason is the bug upstream all the way in [Angular compiler](https://github.com/angular/angular/issues/20931).

Until that bug is fixed and release in all toolchain stream (`@angular/compiler` -> `@angular/cli` -> `ng-packagr`) you should use special NPM tag - `@no-barrels`.

After the fix published and you have switched all your tolling to fixed versions - you can simply jump back on `@latest` NPM tag.

In the mean time all new minor features and patches will be back-ported to `@no-barrels` NPM tag.

---

Thanks to @berrygoudswaard for reporting the [issue with PR](https://github.com/gund/ng-dynamic-component/pull/365) that is now on fixed NPM tag.

Also you can check the [xi18n issue](https://github.com/gund/ng-dynamic-component/issues/368) that was confirmed to be resolved by fixed NPM tag.

**Comment by roopeshreddy** [comment]
We've tried the tag - `^6.1.1-no-barrels.1` and looks like this issue is resolved. Are you planning push it to stable release?

**Comment by gund** [comment]
Since the issue upstream was resolved I'm closing this one.
No more `@no-barrels` releases are planned and should not be necessary anymore.
