### ISSUE TITLE
Handling of :leave transition doesn't work

### ISSUE THREAD

**Issue by tsarevpp** [gund/ng-dynamic-component#372]
Hi Alex,
I am trying to use your library to create a dialog with multiple steps. It works great so far, however, there is a problem with the `:leave` transition, which is called when component leaves the DOM. I'm not sure whether this is a problem with my code or the library isn't waiting for `ngDestory` to be executed when component is changed. Here is a little snippet to reproduce:
```typescript
@Component({
  selector: 'app-parent',
  template: `<div><ndc-dynamic [ndcDynamicComponent]="steps[currentStep]"></ndc-dynamic><button (click)="nextStep()"></button></div>`,
  styleUrls: [`file-upload-page.component.scss`],
})
export class ParentComponent {
  public steps = [ChildOneComponent, ChildTwoComponent]
  public currentStep = 0;
  nextStep(): void {
      // This is called from an output event emitter.
      this.currentStep++;
  }
}
```

The components inside are using:
```typescript
@Component({
  selector: 'app-child-one',
  template: `<div style="width:10rem;height:10rem;background:red;margin: 0 auto;"></div>`,
  animations: [
    trigger('animation', [
      transition(':leave', [
        style({transform: `translateX(0%)`}),
        animate('1000ms', style({transform: `translateX(66%)`})),
      ]),
      transition(':enter', [
        style({transform: `translateX(-66%)`}),
        animate('1000ms', style({transform: `translateX(0)`})),
      ])
    ]),
  ],
})
export class ChildOneComponent{
  ...
}
```

**Comment by gund** [comment]
Hi, well when you are rendering components dynamically you should treat them the same way as when you are rendering them say via router. And to animate dynamic components you basically have to apply the same technique as when animation router components - you need to wrap rendering of components in a DOM element and attach to it animation with queries that will find dynamic components in it.

I have a working demo for you [here](https://stackblitz.com/edit/angular-ndc-animations?file=src%2Fapp%2Fapp.component.ts).

Please note the usage of the `query` function in animation as this is the key to apply animation on dynamic components.

**Comment by tsarevpp** [comment]
Thank you, that is great!
