### ISSUE TITLE
Angular v10 with v7.x version of ng-dynamic-component

### ISSUE THREAD

**Issue by roopeshreddy** [gund/ng-dynamic-component#380]
`import { DynamicComponentModule } from 'ng-dynamic-component';` is throwing has no exported member 'DynamicComponentModule'.ts(2305) error.

**I'm using the ng-dynamic-component@^7.0.1**

**Comment by gund** [comment]
Yes, this was a breaking change as described in the [changelogs](https://github.com/gund/ng-dynamic-component/blob/master/CHANGELOG.md#700-2020-06-28).

You should now use `DynamicModule` to get the component.

**Comment by roopeshreddy** [comment]
Thanks @gund 

I'm now getting this below error - 

> Unexpected value 'undefined' imported by the module 'DynamicModule in project/node_modules/ng-dynamic-component/ng-dynamic-component.d.ts'

This was working fine with Angular v9.x and ng-dynamic-component v6.x-barrels.

NOTE: I'm building a library and this was part of it.

**Comment by gund** [comment]
You need to use `@no-barrels` NPM tag for v7 as well.

**Comment by roopeshreddy** [comment]
Thanks @gund  It was resolved with this!
