### ISSUE TITLE
Can't bind to 'ndcDynamicAttributes' 

### ISSUE THREAD

**Issue by maranmaran** [gund/ng-dynamic-component#381]
Using DynamicIoModule

and defining this
```
@Component({
  selector: 'my-component',
  template: `<ng-template [ngComponentOutlet]="component"
                           [ndcDynamicAttributes]="attributes
                           ></ng-template>`
})
class MyComponent {
  component = MyDynamicComponent1;
  attributes = {...};
}

```
I get thrown an error in console that I can't bind ndcDynamicAttributes to ng-template

My previous configuration looked like 
```
<ndc-dynamic [ndcDynamicComponent]="component"
                           [ndcDynamicAttributes]="attributes
                           ></ndc-dynamic>
```

However, in latest v7 using Angular 10 I can't import `DynamicComponentModule` because it's not exported anywhere. 

What am I missing?

**Comment by maranmaran** [comment]
Ok I believe I got it to work

Imported DynamicModule solo

usage:
```

@Component({
  selector: 'my-component',
  template: `<ng-template [ngComponentOutlet]="component"
                           [ndcDynamicAttributes]="attributes
                           ></ng-template>`
})
class MyComponent {
  component = MyDynamicComponent1;
  attributes = {...};
}
```

Is this correct.. ? Seems to be working fine.

**Comment by gund** [comment]
If you are using v7 - all directives were separated into their own modules.

So if you just need dynamic inputs - `DynamicIoModule`
If you also need dynamic attributes - `DynamicAttributesModule`

I also updated readme to reflect that change.

**Comment by gund** [comment]
Closing this. If you are having another issue please open a new issue.
