### ISSUE TITLE
Passing node content via ndcDynamicContent

### ISSUE THREAD

**Issue by locinus** [gund/ng-dynamic-component#41]
Hi !
Inputs and outputs work great on my dynanic elements! However, I can't get to pass the content of the node to the dynamic component.

Here's my context: I've developped a TrialComponent, aimed at trying different look&feel of various component, by switching them dynamically (via a button next to the TrialComponent). The simplified structure is:

**Application component offering some trial on some components**

    ...
    <comp-trial 
      [inputs]="{ title:'...' }"
      [outputs]="{ click: onClick }"
    >
		This is some content for the dynamic components
	</comp-trial>
    ...

**Trial Component**

	@Component({
		selector: 'comp-trial',
		template: '
		  <ndc-dynamic 
			[ndcDynamicComponent]="dynamicComponent"
			[ndcDynamicInputs]="inputs"
			[ndcDynamicOutputs]="outputs"
		  >
		  </ndc-dynamic>
		'
	})
	export class TrialComponent {
	  dynamicComponent; // the component to insert dynamically (management of this var is not developed here)
	  @Input() inputs: Array<any>;
	  @Input() outputs: Array<any>;
	}

**One of the dynamic component**

	@Component({
	  selector: 'dyn-comp1',
	  template: '
		<div>{{ title }}</div>
		<div class="content"> ...? </div>
	  '
	})
	export class ExpandablePanel1Component extends ExpandablePanel {
	   @Input() title;
	   @Input() items;
	   @Output() click;
	}

I've tried to use ndcDynamicContent on my TrialComponent, but couldn't get to make it work.

Any advice to pass some node content to the dynamic components?

**Comment by gund** [comment]
We to pass the content you need to specify where that content will go in the component (in your case in `comp-trial` and in `dyn-comp1`).

You can do that by placing `<ng-content></ng-content>`.
This technique is called Content Projection.

But since you have to pass that content from your `comp-trial` you can try to create a local template variable on that content, and then forward it to dynamic component:

comp-trial:
```html
<!-- Make sure this piece is hidden from user -->
<ng-content #content></ng-content>
<ndc-dynamic 
		[ndcDynamicComponent]="dynamicComponent"
		[ndcDynamicInputs]="inputs"
		[ndcDynamicOutputs]="outputs"
                [ndcDynamicInputs]="[[content]]"
	  >
	  </ndc-dynamic>
```

dyn-comp1:
```html
<div>{{ title }}</div>
<div class="content"><ng-content></ng-content></div>
```

And btw, your types in `TrialComponent` of inputs and outputs properties are incorrect, instead of `Array<any>` they should be objects (`{[key: string]: any}`).

Cheers.

**Comment by locinus** [comment]
Thanks for a quick reply !

Nice trick to create the local variable on content. However, adapting my code that way (and considering you meant to write:

> [ndcDynamic**Content**]="[[content]]"

), I get the following error:

> TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

I don't know the [[ ]] syntax, so I tried with
 
> [ndcDynamic**Content**]="content"

No error this time, but the content does not appear in my final component (dyn-comp1), even though it does appear in the added not-yet-hidden ng-content node of the Trial component (comp-trial).

**Comment by gund** [comment]
I suspect that the local variable might be of type `TemplateRef`. In that case you can try to access property `nativeElement` to pass into `ndcDynamicContent`.

Also in `comp-trial` you can try to query-select `ng-content` by that local template variable name and console log it on `AfterContentInit` hook to see exactly what you get.

This was always tricky part to forward real content that way and I never saw an example in official Angular docs how to do it although they have exactly the same support on `NgComponentOutlet` directive...

**Comment by locinus** [comment]
Ok, so after trying few things, it seems that a `ng-content` node is not a valid node to pass to `ndcDynamicContent`. So I wrapped it in another proper node, and it works fine now.

My working code, for the archives:

**Trial Component**

	@Component({
		selector: 'comp-trial',
		template: '
		  <div style="display:none">
			<span #mycontent>
			  <ng-content></ng-content>
			</span>
		  </div>      
		  <ndc-dynamic 
			[ndcDynamicComponent]="dynamicComponent"
			[ndcDynamicInputs]="inputs"
			[ndcDynamicOutputs]="outputs"
			[ndcDynamicContent]="[[mycontent]]"
		  >
		  </ndc-dynamic>
		'
	})
	export class TrialComponent {
	  dynamicComponent; // the component to insert dynamically (management of this var is not developed here)
	  @Input() inputs: Array<any>;
	  @Input() outputs: Array<any>;
	}

**One of the dynamic component**

	@Component({
	  selector: 'dyn-comp1',
	  template: '
		<div>{{ title }}</div>
		<div class="content"> <ng-content></ng-content> </div>
	  '
	})
	export class ExpandablePanel1Component extends ExpandablePanel {
	   @Input() title;
	   @Output() click;
	}

**Using the trial component**

	...
	<comp-trial 
	  [inputs]="{ title:'...' }"
	  [outputs]="{ click: myOnClickHandler }"
	>
		This is some content for the dynamic components
	</comp-trial>
	...

Thanks for the help, and the library !

**Comment by gund** [comment]
Great!
Thanks for sharing the solution, very helpful 👍

**Comment by narendrapandey999** [comment]
Hello, 
In my case Trial Component (dummy-spawner) is being called from another component and in their I am setting data like below - 

 <dummy-gridster-item [item]="{cols: 1, rows: 1, y: 0, x: 5}">
      <dummy-spawner [input_component]= "component" [received_input_data]= "input" (output_data)='changereceived($event)' fxFlex="30%">
      <dummy-header #CardHeader>
       <dummy-title>{{header}}</dummy-title>
        </dummy-header>
        <dummy-content>
          <section fxLayout="column"  fxLayoutAlign="center center">
            <dummy-metric dummyMetricScale="xxl" align="center">
              {{content}}
            <dummy-metric-detail>users</dummy-metric-detail>
            </dummy-metric>
          </section>
        </dummy-content>
        <dummy-footer fxLayoutAlign="start" >
          {{footer}}
        </dummy-footer>
      </dummy-spawner>
    </dummy-gridster-item>

Here dummy-spawner is Trial component. Below is my dynamic component - 

<mat-card >
  <mat-card-header >
    <ng-content select="dummy-header"></ng-content>
  </mat-card-header>
  <mat-card-content>
    <ng-content select="dummy-content"></ng-content>
  </mat-card-content>
  <mat-card-footer>
    <ng-content select="dummy-footer"></ng-content>
  </mat-card-footer>
 
</mat-card>

So i am have received value from dynamic component emit event and have saved them in header, footer and content of dummy-gridster-item component. I am trying to add these values directly using "{{header}}". But it doesn't work.

I have used above approach and added the class manually in above ndc-dynamic imports. But i am trying to avoid that. Is there any other way so that I could maintain the styling as well making less changes caller component(dummy-gridster-item component)

**Comment by gund** [comment]
Please provide live example of your problem on stackblitz.com then I might have a look.

**Comment by narendrapandey999** [comment]
Hello Gund, Below is the stackblitz url. 

https://stackblitz.com/edit/angular-with-ng-dynamic-component-c6vexd

It is currently having some import issue hence not working correctly. 
In it, I am passing data from my app component to a spawner component. Spawner component spawn the component received and call its HelloTwComponent.execute() method. It emits back data to output() method of spawner component and then again spawner component emits back to app component changereceived() method.
I am trying to use this received data and component to set data in app.component.html => Card-header.
Cad-header content is input to HelloTwoComponent. I am trying to inject value for HelloTwoComponent through appComponent's html. As HelloTwoComponent have more component embedded to it and expects ng-content input of those components, i am following such approach.

**Comment by gund** [comment]
@narendrapandey999 I had a look into your plunkr.

First of all there were some errors not related at all to my library (some angular-cdk errors) that I had to fix.

Finally I upgraded my library from v1.1.0 (which is quite outdated) to v3.1.1 and took advantage of `(ndcDynamicCreated)` output that allowed me to get a reference to created component and then execute it's method.

One important thing to note is that when `(ndcDynamicCreated)` output emits outputs are not yet bound to your component so you should wait one JS tick to then trigger your emit (via `setTimeout`).

Here's the fixed version: https://stackblitz.com/edit/angular-with-ng-dynamic-component-k4olqc?file=app%2Fspawner.component.ts

**Comment by narendrapandey999** [comment]
Hello Gund, thanks for the working code.
I am still facing issue with spawning as the rendered data from child component is being set in my code but it still doesn't get spawned in web page. Could there be a possible object initialisation issue as my app_component have a  ngAfterViewChecked() call (I have to add this check to get recent modifications from child component) and ndcDynamicCreated.instacne.execute() gets called quite later.
In my code, i was calling execute() function of child through OnInit() block. I have replaced that part with ndcDynamicCreated.instacne.execute() and have removed that code from OnInit call.

To debug this issue, i tried adding hard coded value in <card-title>123</card-title> in app_component.html. It surely gets reflected in plunkr but not in actual code. any thoughts what else could be missing

**Comment by narendrapandey999** [comment]
Also, is it mandate to use ndcDynamicCreated or if we can invoke the underlying method of child component through other means. For eg, making part of ngOnInit()

**Comment by narendrapandey999** [comment]
Ok. After lot of hit n trial , it worked. I was missing <div> tag in my projected content (as you have mentioned in :( ). So i enclosed my child component html with <div> tag and it worked. It didn't took the styling as required , but it seems specific to our project. Thanks again :)
