### ISSUE TITLE
can't get directives to render

### ISSUE THREAD

**Issue by elubinenaptive** [gund/ng-dynamic-component#419]
I am on v6.1.1 with angular 9.

from a component, I query some HTML from my server that needs to render on my page. The HTML includes some angular components.

I am trying to use ng-dynamic to load this html into a Render component which then should display the html on the page and dynamically also create the needed components. I think I need to pass in ndcDynamicDirectives for each special component we designed, but i get "Cannot read property 'update' of undefined" for any component I pass into "ndcDynamicDirectives".

Is this even the correct use case for ng-dynamic-component with ndcDynamicDirectives?

I'm looking for any sample code that can render html from my component into a dynamic component with other components in the html.

thanks!

**Comment by gund** [comment]
If I understood correctly you want to render angular components as just html tags on se server and then paste them into the page?

If yes then this is not the library for it. You most likely need to use web components.

You can check [Angular Elements](https://angular.io/guide/elements) to learn how you can convert your angular components into native web components.

**Comment by elubinenaptive** [comment]
no, sorry, wasn't clear... i want to query a component's template from my server. i want them to render in normal angular style.

<h1>hello</h1>

but it will also contain some custom elements

<my-element>hello</my-element>

**Comment by elubinenaptive** [comment]
seems like I'm confusing topics here... sorry. I thought I might need the Experimental Directives in order to render other components within the dynamically loaded component. But if not, then how do i get the dynamically loaded component to render other components like <my-element>?

`<ndc-dynamic [ndcDynamicComponent]="component" [ndcDynamicInputs]="{content:content}"></ndc-dynamic>`

```
public component = HelloComponent;
public content: string;
public ngOnInit() {
   this.http.get<string>(...).subscribe(
      (resp: string) => {
          this.content= resp.content;     // "<h1>hello</h1><my-element>hello</my-element>"
      });
}
```

**Comment by gund** [comment]
As you might know you cannot get random HTML from anywhere and just render it in your Angular Components.
And this library is not for that purpose either.
What you want to do can be solved via Web Components so you should check them out.

I will close this issue as it is irrelevant to this library.
