### ISSUE TITLE
Doesn't work with ngComponentOutlet

### ISSUE THREAD

**Issue by elclanrs** [gund/ng-dynamic-component#42]
Any ideas why this won't work?

```
<ng-container *ngIf="item?.component; else elseBlock">
  <ng-container *ngComponentOutlet="item.component"
                [ndcDynamicInputs]="item.inputs">
  </ng-container>
</ng-container>
```

Works fine if I use `<ndc-dynamic>` and `[ndcDynamicComponent]`. I also tried with a `div` instead of `ng-container`, but not luck...

**Comment by gund** [comment]
This is how you can use it:
```html
<ng-container *ngIf="item?.component; else elseBlock">
  <ng-template
    [ngComponentOutlet]="item.component"
    [ndcDynamicInputs]="item.inputs"
  ></ng-template>
</ng-container>
```

**Comment by elclanrs** [comment]
@gund, thanks for the quick reply, that worked great! I have another question related to this. I thought that using `ngComponentOutlet` I'd be able to use `entryComponents` instead of `DynamicModule.withComponent`, but it didn't work as I expected. This is what I did:

```
imports: [
  DynamicModule,
  ...
],
declarations: [MyComponent],
entryComponents: [MyComponent]
```

But I couldn't get it working. I want to have a smooth transition for when Angular natively supports inputs/outputs with `ngComponentOutlet`.

Any suggestions?

**Comment by gund** [comment]
It should work either by passing components to `DynamicModule.withComponent` or to `entryComponents`.
Both methods are telling Angular to produce component factories.

And as far as I know angular team does not currently consider implementing inputs/outputs, although it might change in the future like with http interceptors...
