### ISSUE TITLE
ndcDynamicOutputs: call markForCheck after handler is called

### ISSUE THREAD

**Issue by ajafff** [gund/ng-dynamic-component#429]
Angular Version: 11.0.9
ng-dynamic-component: 8.0.0

https://stackblitz.com/edit/angular-ivy-bky9qc?file=src/app/app.component.ts

The example uses `ChangeDetectionStrategy.OnPush`. The dynamic component emits the `valueChange` event async after `ngOnInit`. The `handleValueChange` handler is called correctly, but `AppComponent` is not marked for check, therefore the initial value is not displayed.

If you comment out `changeDetection: ChangeDetectionStrategy.OnPush` or uncomment `this.cd.markForCheck()` it works.

Since Angular always marks a component for check when an event handler in the template is executed, I would have expected this library to do the same.

I imagine this could be as easy as injecting `ChangeDetectorRef` and calling `markForCheck` when a handler is called.

**Comment by gund** [comment]
Hey @ajafff, thanks for great examples.

Yes this seems reasonable and somehow I did not pay attention to this fact although knew about it as well.

This should be an easy fix actually, so if you want to submit a PR I would be happy to accept it =)
