### ISSUE TITLE
Maximum call stack size exceeded angular 10

### ISSUE THREAD

**Issue by ameza** [gund/ng-dynamic-component#456]
I get the above error when the package is added to an angular 10 project, no other details are provided, the site compiles fine if the package usage is removed

**Comment by gund** [comment]
Hey, I would need more that this to be able to help you.
At least versions used and stack straces and ideally reproduction in online sandboxe like stackblitz.

**Comment by alexiadorneles** [comment]
Hi @gund I am facing a similar issue, I described exactly what's happening here: https://github.com/gund/ng-dynamic-component/issues/460

**Comment by gund** [comment]
I'm closing this issue as it's outdated.
If you want to reopen the discussion please feel free to open a new issue.
