### ISSUE TITLE
Maximum call stack size exceeded in library project

### ISSUE THREAD

**Issue by alexiadorneles** [gund/ng-dynamic-component#460]
Hello,

I am currently using this package inside my library project. The configuration is the following:

Angular: 11
Builder: ng-packagr
ng-dynamic-component: ^8.0.1

When I try to build my library I am receiving the error: `Maximum call stack size exceeded`. If I remove the ng-dynamic-component imports from my files and modules, the build works properly. An example of imports I have on my project:

`import { InputsType, OutputsType } from 'ng-dynamic-component'; --> causes error Maximum call stack size exceeded, if removed error goes away
`
```
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import {DynamicModule} from 'ng-dynamic-component/lib/dynamic.module';
import { SomeComponent } from './some.component';

@NgModule({
  declarations: [SomeComponent],
  exports: [SomeComponent],
  imports: [CommonModule, DynamicModule], --> causes error Maximum call stack size exceeded, if removed error goes away
})
export class SomeModule {}
```

My ng-packagr config:
```
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/some-system",
  "lib": {
    "entryFile": "src/public-api.ts",
  },
  "assets": ["assets/**/*.*"]
}
```

**Comment by nailtonvieira** [comment]
Same problem here @alexiadorneles 

Angular CLI: 11.2.14
Node: 14.17.3
OS: darwin x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.2
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@angular/cdk                    11.2.13
@angular/material               11.2.13
@schematics/angular             11.2.14
@schematics/update              0.1102.14
ng-packagr                      12.1.0
rxjs                            6.6.3
typescript                      4.0.5
webpack                         4.46.0

**Comment by roopeshreddy** [comment]
Same issue with Angular v12 and v9  as per the docs.

**Comment by gund** [comment]
If you are facing this you can switch to `no-barrels` NPM tag, see https://github.com/gund/ng-dynamic-component/issues/369

**Comment by roopeshreddy** [comment]
Unfortunately, this issue is still exists with barrel on Angular v12 Library!

**ng-dynamic-component@10.1.1-no-barrels.1**
