### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by TheCelavi** [gund/ng-dynamic-component#461]
Does anyone knows if this project is abandoned?

**Comment by th0r** [comment]
Have the same question. Does anyone know of any alternative?

**Comment by TheCelavi** [comment]
We have a fork that we use inside company: https://github.com/evermed/ng-dynamic-component 

We are not happy about this, we didn't setup auto deploy and testing of component, as we still hope that this project will continue its development. 

We will maintain fork until someone from this project with admin privileges provide us with info what is happening with this project. 

Either way - this is awesome lib, should not be abandoned. I wonder why angular did not provide something similar as part of its core.

**Comment by gund** [comment]
Hey folks! I'm sorry for not being active recently as I was dealing with some other stuff offline.
Now that I'm back I will take care of the latest issues and upgrade it for latest Angular.
Cheers!
