### ISSUE TITLE
Question about dynamic templates

### ISSUE THREAD

**Issue by Yago-Ferrer** [gund/ng-dynamic-component#466]
This is a fantastic project! I was wondering if it's possible to create a MyDynamicComponent1 programmatically so that I can have a custom template as well. 
Thanks!

**Comment by gund** [comment]
Hey there!

I don't think you can create templates dynamically as any component must be compiled by angular at build time.

And since ivy all angular apps don't ship jit compiler so you cannot compiler templates dynamically at runtime.

**Comment by Yago-Ferrer** [comment]
Thank you for your answer @gund. I was not able to find anything useful. I'm using Vue at the moment, but ideal but it works.
