### ISSUE TITLE
Support RxJS ^7.4.0

### ISSUE THREAD

**Issue by martibenn** [gund/ng-dynamic-component#467]
Since Angular support RxJS `^7.4.0` with `@angular/common@13.1.X`, would it be possible to upgrade ng-dynamic-component peer dependency on @angular/common and RxJS ?

Angular RxJS version : https://unpkg.com/browse/@angular/core@13.1.1/package.json
![2021-12-16-15-21-01](https://user-images.githubusercontent.com/60661999/146389125-25948da1-dc53-43e0-9fc6-e8af5b322b08.png)

ng-dynamic-component RxJS &@angular/common peer dependency : 
https://github.com/gund/ng-dynamic-component/blob/4bb0ed2b3fa88197a9bfe9b0edb95160f1015214/projects/ng-dynamic-component/package.json#L21
https://github.com/gund/ng-dynamic-component/blob/4bb0ed2b3fa88197a9bfe9b0edb95160f1015214/projects/ng-dynamic-component/package.json#L23

The error when adding ng-dynamic-component@10.0.0 on a 13.1.1 Angular problem :
![npm](https://user-images.githubusercontent.com/60661999/146396203-ae442a0c-4a22-462f-bc68-e74d8014a614.png)

Thanks !

**Comment by martibenn** [comment]
Seems `peerDependencies` on `@angular/common` is the culprit :
https://github.com/gund/ng-dynamic-component/blob/4bb0ed2b3fa88197a9bfe9b0edb95160f1015214/projects/ng-dynamic-component/package.json#L21

![npm](https://user-images.githubusercontent.com/60661999/146396203-ae442a0c-4a22-462f-bc68-e74d8014a614.png)

**Comment by gund** [comment]
Hey @martibenn, thanks for the suggestion!
Yes we can add support for rxjs v7 to peer deps!
And we do not need to do any changes to angular deps as it allows any v13 version.
