### ISSUE TITLE
Support for Angular 14

### ISSUE THREAD

**Issue by stijnvn** [gund/ng-dynamic-component#469]
Can you update ng-dynamic-component to support Angular 14?

**Comment by gund** [comment]
Yes, however the current version should also work just fine with angular v14. Did you try to use it?

**Comment by stijnvn** [comment]
I have got an npm error that it was not compatible with Angular 14.

**Comment by stijnvn** [comment]
I guess you should just update the dependency on Angular

```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0 || ^13.0.0" from ng-dynamic-component@10.1.0
npm ERR! node_modules/ng-dynamic-component
npm ERR!   ng-dynamic-component@"10.1.0" from the root project
```

**Comment by gund** [comment]
@stijnvn could you please try to install version `10.2.0-next.1` and see if the problem is solved?
Once it's confirmed I will release it as latest.
