### ISSUE TITLE
Building app with angular 13 leads to compile error

### ISSUE THREAD

**Issue by sotjdisc** [gund/ng-dynamic-component#473]
./node_modules/ng-dynamic-component/fesm2015/ng-dynamic-component.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string 'Y:\inventory\inventory-web-ui\node_modules\ng-dynamic-component\fesm2015\ng-dynamic-component.mjs: This application depends upon a library published using Angular version 14.0.1, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  26 | }
  27 | /** @nocollapse */ ComponentOutletInjectorDirective.├ë┬╡fac = i0.├ë┬╡├ë┬╡ngDeclareFactory({ minVersion: "12.0.0", version: "14.0.1", ngImport: i0, type: ComponentOutletInjectorDirective, deps: [{ token: i1.NgComponentOutlet, host: true }], target: i0.├ë┬╡├ë┬╡FactoryTarget.Directive });
> 28 | /** @nocollapse */ ComponentOutletInjectorDirective.├ë┬╡dir = i0.├ë┬╡├ë┬╡ngDeclareDirective({ minVersion: "14.0.0", version: "14.0.1", type: ComponentOutletInjectorDirective, selector: "[ngComponentOutlet]", providers: [
     |                                                            ^
  29 |         {
  30 |             provide: DynamicComponentInjectorToken,
  31 |             useExisting: ComponentOutletInjectorDirective,'
    at run (Y:\inventory\inventory-web-ui\node_modules\@babel\core\lib\transformation\index.js:37:15)
    at run.next (<anonymous>)
    at Function.transform (Y:\inventory\inventory-web-ui\node_modules\@babel\core\lib\transform.js:25:41)
    at transform.next (<anonymous>)
    at step (Y:\inventory\inventory-web-ui\node_modules\gensync\index.js:261:32)
    at Y:\inventory\inventory-web-ui\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (Y:\inventory\inventory-web-ui\node_modules\gensync\index.js:223:11)
    at Y:\inventory\inventory-web-ui\node_modules\gensync\index.js:189:28
    at Y:\inventory\inventory-web-ui\node_modules\@babel\core\lib\gensync-utils\async.js:74:7
    at Y:\inventory\inventory-web-ui\node_modules\gensync\index.js:113:33

Error: node_modules/ng-dynamic-component/lib/component-injector/component-outlet-injector.directive.d.ts:10:18 - error TS2314: Generic type '├ë┬╡├ë┬╡DirectiveDeclaration' requires 6 type argument(s).

10     static ├ë┬╡dir: i0.├ë┬╡├ë┬╡DirectiveDeclaration<ComponentOutletInjectorDirective, "[ngComponentOutlet]", ["ndcComponentOutletInjector"], {}, {}, never, never, false>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ng-dynamic-component/lib/dynamic-attributes/dynamic-attributes.directive.d.ts:28:18 - error TS2314: Generic type '├ë┬╡├ë┬╡DirectiveDeclaration' requires 6 type argument(s).

28     static ├ë┬╡dir: i0.├ë┬╡├ë┬╡DirectiveDeclaration<DynamicAttributesDirective, "[ndcDynamicAttributes],[ngComponentOutletNdcDynamicAttributes]", ["ndcDynamicAttributes"], { "ndcDynamicAttributes": "ndcDynamicAttributes"; "ngComponentOutletNdcDynamicAttributes": "ngComponentOutletNdcDynamicAttributes"; }, {}, never, never, false>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: node_modules/ng-dynamic-component/lib/dynamic-directives/dynamic-directives.directive.d.ts:59:18 - error TS2314: Generic type '├ë┬╡├ë┬╡DirectiveDeclaration' requires 6 type argument(s).

59     static ├ë┬╡dir: i0.├ë┬╡├ë┬╡DirectiveDeclaration<DynamicDirectivesDirective, "[ndcDynamicDirectives],[ngComponentOutletNdcDynamicDirectives]", never, { "ndcDynamicDirectives": "ndcDynamicDirectives"; "ngComponentOutletNdcDynamicDirectives": "ngComponentOutletNdcDynamicDirectives"; }, { "ndcDynamicDirectivesCreated": "ndcDynamicDirectivesCreated"; }, never, never, false>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ng-dynamic-component/lib/dynamic-io/dynamic-io.directive.d.ts:20:18 - error TS2314: Generic type '├ë┬╡├ë┬╡DirectiveDeclaration' requires 6 type argument(s).

20     static ├ë┬╡dir: i0.├ë┬╡├ë┬╡DirectiveDeclaration<DynamicIoDirective, "[ndcDynamicInputs],[ndcDynamicOutputs],[ngComponentOutletNdcDynamicInputs],[ngComponentOutletNdcDynamicOutputs]", never, { "ndcDynamicInputs": "ndcDynamicInputs"; "ngComponentOutletNdcDynamicInputs": "ngComponentOutletNdcDynamicInputs"; "ndcDynamicOutputs": "ndcDynamicOutputs"; "ngComponentOutletNdcDynamicOutputs": "ngComponentOutletNdcDynamicOutputs"; }, {}, never, never, false>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: node_modules/ng-dynamic-component/lib/dynamic.component.d.ts:18:18 - error TS2314: Generic type '├ë┬╡├ë┬╡ComponentDeclaration' requires 7 type argument(s).

18     static ├ë┬╡cmp: i0.├ë┬╡├ë┬╡ComponentDeclaration<DynamicComponent<any>, "ndc-dynamic", never, { "ndcDynamicComponent": "ndcDynamicComponent"; "ndcDynamicInjector": "ndcDynamicInjector"; "ndcDynamicProviders": "ndcDynamicProviders"; "ndcDynamicContent": "ndcDynamicContent"; }, { "ndcDynamicCreated": "ndcDynamicCreated"; }, never, never, false>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by sotjdisc** [comment]
The problem is that 10.1.0 is also somehow corrupt and needs Angular 14...

**Comment by gund** [comment]
Yeah that's probably the reason, up until v14 there was an issue with the barrel exports so you are using correct version.
I will update the docs about compatibility with Angular v13 accordingly.

**Comment by gund** [comment]
@willyboy it's still there just hidden inside of a collapsible element:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/3644678/192656752-3f3d54d7-0044-434f-9130-b08a5f3fd5b7.png">
