### ISSUE TITLE
Cannot access 'IoService' before initialization

### ISSUE THREAD

**Issue by menelai** [gund/ng-dynamic-component#480]
Uncaught ReferenceError: Cannot access 'IoService' before initialization

/node_modules/ng-dynamic-component/fesm2015/ng-dynamic-component.mjs
/node_modules/ng-dynamic-component/fesm2020/ng-dynamic-component.mjs

Both on line 31

**Comment by gund** [comment]
Hey, what version of the lib and Angular are you using?
Also would be nice to have a repro repo online on stackblitz.

**Comment by gund** [comment]
Ok I've [created a demo](https://stackblitz.com/edit/ndc-dynamic-component-example?file=src%2Fapp%2Fapp.component.ts) myself and can reproduce the issue too.
Seems like a bug indeed.

**Comment by menelai** [comment]
I use v 14.2.
Here is stackblitz:
https://stackblitz.com/edit/angular-ivy-wzah9d

**Comment by viacheslavsaloid** [comment]
The same for me.

Angular: 14.1.3

It works fine on 10.3.1
But broken on 10.5.0

**Comment by gund** [comment]
Could you please try the next version and let me know if it works?
For some reason stackblitz cannot resolve latest next version...

**Comment by gund** [comment]
Ok, I was able to verify this on stackblitz and it's fixed on next, so I will go ahead and release it on latest tag.
