### ISSUE TITLE
Support for Angular 15

### ISSUE THREAD

**Issue by msgoloborodov** [gund/ng-dynamic-component#493]
Can you update ng-dynamic-component to support Angular 15, please?

**Comment by gund** [comment]
You should be able to just use the latest version with Angular 15 as is, unless there is some error you are getting?

**Comment by msgoloborodov** [comment]
Yes, it works fine with Angular 15, but Angular 14 also installed.
So it will be nice to have version of ng-dynamic-component with angular 15 in deps.

**Comment by gund** [comment]
But the library does not install angular in it's dependencies, only references angular as a peer dependency:
https://github.com/gund/ng-dynamic-component/blob/5df76ff9cb2f7a3c52a44e93a9e9bac9e9c2c9ce/projects/ng-dynamic-component/package.json#L20-L27

So I'm not quite sure this is a problem of this package as it's version range is compatible with Angular 14+.

**Comment by msgoloborodov** [comment]
Fine! Sorry, I looked at another package.json in a root dir.

**Comment by msgoloborodov** [comment]
Fine! Sorry, I looked at another package.json in a root dir.
