### ISSUE TITLE
[BUG] `IoEventContextToken` is not exported

### ISSUE THREAD

**Issue by daweedm** [gund/ng-dynamic-component#503]
**Describe the bug**

`IoEventContextToken` is not exported in the public API.
```bash
TS2305: Module '"ng-dynamic-component"' has no exported member 'IoEventContextToken'.
```

The following does not work : 
```ts
import {IoEventContextToken} from "ng-dynamic-component";
```
Editor's import autocomplete generate the following instead : 
```ts
import {IoEventContextToken} from "ng-dynamic-component/lib/io/event-context";
```
which produces the following error 
```bash
 Error: Module not found: Error: Package path ./lib/io/event-context is not exported from package /usr/src/app/node_modules/ng-dynamic-component (see exports field in /usr/src/app/node_modules/ng-dynamic-component/package.json)
```

**Expected behavior**
`IoEventContextToken` should be available from the public API and should be able to be imported like this : 
```ts
import {IoEventContextToken} from "ng-dynamic-component";
```

**Reproduction**
N/A

**Environment:**
 - OS: Debian 12
 - Browser: chrome
 - Library version: 10.6.1
 - Angular version: 15.1.0

**Additional context**
N/A

**Comment by daweedm** [comment]
@gund I found a workaround by using `.bind(this)` directly in the template : 

```html
<ng-template
    [ngComponentOutlet]="PointingScreenItemComponent"
    [ndcDynamicInputs]="{item: item}"
    [ndcDynamicOutputs]="{selected: onItemSelected.bind(this)}"
    *ngFor="let item of items"></ng-template>
```

Since function context binding works in the template, isn't `IoEventContextToken` redundant ?

**Comment by gund** [comment]
@daweedm the `.bind()` workaround for sure works but it's inefficient as this call will be performed every time your component's view is change-detected, so `IoEventContextToken` is meant to optimally do this for you.
As a more performant workaround you can use arrow function for an event handler method on your component so it's already bound by default.

But it's a good catch, the `IoEventContextToken` must be part of the public API.
I will create a fix for this soon.
