### ISSUE TITLE
Property 'withComponents' does not exist on type 'typeof DynamicModule'. 

### ISSUE THREAD

**Issue by Vigneshjana** [gund/ng-dynamic-component#508]
I am facing below issue while compiling 
 
Property 'withComponents' does not exist on type 'typeof DynamicModule'. 

My Module will be like below Screenshot

![Screenshot 2023-07-04 135656](https://github.com/gund/ng-dynamic-component/assets/31133557/e0ea5a3b-81cc-4427-97fe-e248a953416e)

**Environment:**
 - OS: Linux Ubuntu 22.04
 - Browser: chrome
 - Library version: 10.7.0
 - Angular version: 14

**Comment by gund** [comment]
This static method is not needed for long time now, it was [deprecated in v6](https://github.com/gund/ng-dynamic-component/releases/tag/v6.0.0) and removed in v7.
So you should simply drop it and just keep the `DynamicModule` in your imports.
