### ISSUE TITLE
Component not support nested 

### ISSUE THREAD

**Issue by jindovu** [gund/ng-dynamic-component#510]
Hi There!
    I'm using this component for my case, but it's not working for nested component for example: 
     I have 2 tabs with dynamic component (tab 1, tab 2), 
        - when user click to tab 1 -> show component 1
        - click tab 2 -> show component 2
    -> in component 1 and 2 I have more 2 tabs with dynamic components, it's not show correctly, could you please have a look on this?

**Comment by gund** [comment]
Please create a reproduction example either using online tools like stackblitz or a GitHub repo so that I can check it.
Otherwise there is no way to help you.

**Comment by gund** [comment]
Closing this as without more info this is irrelevant.
If you still have issues please open a new issue with example code online showcasing your issue.
