### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by claridgicus** [gund/ng-dynamic-component#513]
Hey @gund 

I'm starting two new projects this upcoming week, and I've specced StoryBlok, just curious if angular support is going to be ongoing before I commit these clients to a build with the platform.

If it is - is there any possibility we can get these components supported versions up to angular 17?

**Comment by gund** [comment]
Hi, I think it is still compatible with Angular v17 just like it has been with previous versions.

But if you are getting any errors feel free to post them here so we can fix them and potentially upgrade to the latest version.

I'm just keeping it as is, as long as it remains forward compatible with Angular versions, but if it's necessary - I will update it.

**Comment by claridgicus** [comment]
My Hero, I've already built out a foundational site with it and the experience has been relatively painless.

My clients being corporates tend to say "I don't like it" if it doesn't have "supports version x" on the box.

**Comment by claridgicus** [comment]
@gund just going through the angular doco for the lazyloading/codesplitting components functionality introduced in 17

https://angular.io/api/core/defer

I'm pretty confident the approach used in the lib wouldn't allow for the code splitting functionality to work correctly, but it would be awesome even just for you to keep it in mind for a future update.

**Comment by gund** [comment]
@claridgicus thanks for the suggestion, however this lib does not try to solve loading of the components so it's pretty much out of scope.
It's up to you to decide how and when you load your components and when you loaded them the lib will help you setup inputs/outputs easily and that's pretty much it - do one thing and do it well =)

I'm gonna close this issue, and if you will have some other problems feel free to open a new issue.
