### ISSUE TITLE
[Bug] Remove ndc-dynamic from the dom using flex gap or add display none

### ISSUE THREAD

**Issue by thebspin** [gund/ng-dynamic-component#514]
**Describe the bug**
Currently when you use flex and gap the presence of the ndc-dynamic tag inside the dom messes with the gaps as you can see on the screenshot. Adding display none to it fixes it, but as far as i am aware i cannot pass a class just to this attribute that gets rended in the dom?

**Expected behavior**
No ndc-dynamic tag in html or being able to pass a class

**Reproduction**
See screenshot

**Screenshots**
<img width="424" alt="image" src="https://github.com/gund/ng-dynamic-component/assets/203133/d56e7c40-1f53-4e6b-aae4-0d3d7dc71ba2">

**Comment by gund** [comment]
If you want custom rendering without a component tag then you should use directive for rendering instead of the component.
See example with [ngComponentOutlet](https://github.com/gund/ng-dynamic-component?tab=readme-ov-file#ngcomponentoutlet).

**Comment by thebspin** [comment]
Awesome missed that in the docs but works nicely, much appreciated for the quick response!
