### ISSUE TITLE
Access to component reference

### ISSUE THREAD

**Issue by roscopeeco** [gund/ng-dynamic-component#55]
Hello
I've read the documentation but there is nothing there about getting access to the dynamic component reference...can this be done and if so how?
thanks
Ross

**Comment by locinus** [comment]
Hi Ross
I've been looking for that myself, and here's a solution using ViewChild on the ndc component itself::

```
import { DynamicComponent } from 'ng-dynamic-component';
@Component({
    template: `
          <ndc-dynamic
            [ndcDynamicComponent]="dynamicComponentType"
          ></ndc-dynamic>
    `
})
export class ContainDynamicComponent {
  @ViewChild(DynamicComponent) ndc: DynamicComponent;
  dynamicComponentType: any;

  // reference on your dynamic component
  dynamicComponent: any;

  setDynamicComponent( type: any ) {
    this.dynamicComponentType = type;

    // we need to postpone the fetching of the reference one tick
    // to make sure the reference has already been calculated
    setTimeout( () => {
      const ref: any = this.ndc.componentRef;
      this.component = ref._component;
      // you can now play with your component directly !
      // this.component.doWonders();
    });
  }
}
```

Works with me, but maybe the author will have a better suggestion.

**Comment by gund** [comment]
If you are using `ndc-dynamic` component to create your dynamic components then you can access `componentRef` public property. It is of type `ComponentRef` so you need to get `instance` property of that one.
Example in HTML:
```html
<ndc-dynamic ndcDynamicComponent="componentType" #component></ndc-dynamic>
Use it like this: {{ component.instance }}
```
Example in TS:
```ts
class MyComponent implements AfterViewInit {
  @ViewChildren(DynamicComponent) component: DynamicComponent;

  ngAfterViewInit() {
    // Use your component here
    console.log(this.component.instance);
  }
}
```

**Comment by roscopeeco** [comment]
Thanks to both of you. I've used @viewchild and @viewchildren but didn't think I could use it with dynamic components...wrong Assumption! 
Cheers
Ross

**Comment by gund** [comment]
@roscopeeco your assumption was not wrong - you cannot query for dynamically created components using  @ViewChild and @ViewChildren, but what you can do is get access to the static component that creates dynamic one and get it's reference from there (that is what me and @locinus posted above)
