### ISSUE TITLE
Destruction of dynamic components

### ISSUE THREAD

**Issue by locinus** [gund/ng-dynamic-component#56]
Hi Alex !

Today I'm wondering how the destruction of the dynamic components are handled; so I know when ngOnDestroy will be called.
More than that, I would need a way to be able to force the destruction of a dynamic component: I have a panel in which I inject a component dynamically via your tool, and then I hide the panel from the interface, but what I would actually need is to effectively destroy the dynamic component (I want to keep the panel alive).

Thank you!

**Comment by gund** [comment]
According to the [spec](https://github.com/gund/ng-dynamic-component/blob/f6e4310ebb9024fcf25508e3fc235e2344406ab3/src/dynamic/dynamic.component.spec.ts#L61) any time you assign `ndcDynamicComponent` input property to null (or undefined) it will destroy created component and Angular itself will take care to call `ngOnDestroy` hook.

**Comment by locinus** [comment]
Indeed !
Thanks for a quick reply!
