### ISSUE TITLE
2 way data binding with ngModel

### ISSUE THREAD

**Issue by ryanbonial** [gund/ng-dynamic-component#60]
Can this be used with a component that has ngModel 2 way binding? It doesn't seem to work when ngModel is added to the inputs and outputs or when ngModel is added to the inputs and ngModelChange is added to the outputs.

Plnkr example:
[http://plnkr.co/edit/DY4delkqeGyl3ElnsRJs?p=preview](http://plnkr.co/edit/DY4delkqeGyl3ElnsRJs?p=preview)

**Comment by gund** [comment]
You have to keep in mind that dynamically created components will not have inputs and outputs to be attached in the DOM and as a consequence you ngModel input wont tell Angular to bind ngModel to the corresponding value accessor - you have to take care about it manually.

So I added 1 more input `ngModel` and 1 output `ngModelChange` in order to simulate what angular will do.

Secondly if you want to have true 2 way binding you cannot directly update ngModel value because it will loose reference to the bounded component instance, instead you have to use `dot construct` like `inputs.ngModel` where `inputs` property will be bound to dynamic component inputs.

Please refer to [updated plunkr](https://plnkr.co/edit/Ph0R4tziwd21NkKWOstA?p=preview) for working example.

**Comment by ryanbonial** [comment]
Thanks for the explanation and updated plunkr. It is a shame that ngModel and ngModelChange have to be implemented manually. I can add the additional Input() and Output() for my own components, but it will be tougher to use 3rd party components that use ngModel.

**Comment by gund** [comment]
@ryanbonial you can always wrap those components in your own component that will proxy `[(ngModel)]` through the Input and Output.

**Comment by maxfahl** [comment]
I solved it by wrapping the control value accessor components in a component of my own. The final class extends this class at it's base:

´´´
export class FormFieldsComponent implements AfterViewInit, OnDestroy {

	@ViewChildren(NgModel)
	formControllers: QueryList<NgModel>;

	@Input()
	public form: NgForm;

	private addedFormControllers: NgModel[];
	private formControllerChangeSub: Subscription;

	constructor() {
		this.addedFormControllers = [];
	}

	ngAfterViewInit(): void {
		this.setupFormControllers();
		this.formControllerChangeSub = this.formControllers.changes.subscribe(
			this.setupFormControllers.bind(this)
		);
	}

	private setupFormControllers(): void {
		this.resetFormControllers();
		if (this.formControllers && this.formControllers.length) {
			this.formControllers.forEach(control => {
				control.name = `${ control.name }_${ Date.now() }`;
				this.addedFormControllers.push(control);
				this.form.addControl(control);
			});
		}
	}

	private resetFormControllers(): void {
		if (this.addedFormControllers) {
			this.addedFormControllers.forEach(
				control => this.form.removeControl(control)
			);
			this.addedFormControllers = [];
		}
	}

	ngOnDestroy(): void {
		this.resetFormControllers();
		this.formControllerChangeSub.unsubscribe();
	}
}
´´´

Then I have another base class for my angular component that is placed between my angular component and the base class above. That class looks like this:

´´´
export class CustomFieldInputBase<T extends CustomField> extends FormFieldsComponent implements OnDestroy {

	@Input()
	customField: T;

	@Input()
	model: any;

	constructor() {
		super();
	}

	ngOnDestroy(): void {
		super.ngOnDestroy();
	}
}
´´´

The input model is an object i will do two way bindings on. The input customField only contains data about the field I'm rendering containing it's name and so on.

An example of my angular component class looks like this:

´´´
@Component({
	selector: 'custom-string-field-input',
	encapsulation: ViewEncapsulation.None,
	providers: [],
	templateUrl: './custom-string-field-input.component.html',
	styleUrls: ['./custom-string-field-input.component.sass']
})
export class CustomStringFieldInputComponent extends CustomFieldInputBase<CustomStringField> implements OnInit, OnDestroy {

	constructor(

	) {
		super();
	}

	ngOnInit(): void {

	}

	ngOnDestroy(): void {
		super.ngOnDestroy();
	}
}

´´´

And its HTML:

´´´
<input name="{{ customField.name }}"
	   placeholder="{{ customField.label }}{{ customField.required ? '*' : '' }}"
	   class="{{ customField.name }}-input"
	   [(ngModel)]="model[customField.name]"
	   [attr.empty]="(!model[customField.name] || !model[customField.name].trim()) ? '' : undefined"
	   [required]="customField.required"
	   autocomplete="off">
´´´

The base class FormFieldsComponent registers any childs of NgModel to the form (inputed to the same class), the they just function as always :)

This may be quite overwhelming for some, but I didn't have much time to post this.
