### ISSUE TITLE
Calling function from parent component

### ISSUE THREAD

**Issue by levinzz** [gund/ng-dynamic-component#62]
How would I go about calling a function from the parent, something like this :

```
@Component({
    template: `<button (click)="doStuff()">Do something</button>
               <ng-container *ngComponentOutlet="dynamicComponent;
                              ndcDynamicInputs: inputs;
                              ndcDynamicOutputs: outputs"></ng-container>`
})
export class ParentComponent {
     dynamicComponent = ChildComponent1;
     inputs = {};
     outputs = {};

     doStuff = () => {
        //Do stuff

        //Call child component doStuff function
     }
}

@Component({ ... })
export class ChildComponent1{
    doStuff = () => {  ...  }
}

```

One workaround I can think of, would be by changing an input value, thus triggering Angular change detection and implementing ngOnChanges in the child component but I don't think it's really nice.

**Comment by gund** [comment]
I believe the best approach will be to get direct reference to your dynamic component and simply call method on it.
Please refer to [this issue](https://github.com/gund/ng-dynamic-component/issues/55) on how to do it.

**Comment by levinzz** [comment]
I changed :
```
<ng-container *ngComponentOutlet="dynamicComponent;
                                    ndcDynamicInputs: inputs;
                                    ndcDynamicOutputs: outputs"></ng-container>
```
To : 
```
<ndc-dynamic [ndcDynamicComponent]="dynamicComponent"
                 [ndcDynamicInputs]="inputs"
                 [ndcDynamicOutputs]="outputs"></ndc-dynamic>
```

Then in the corresponding ts component file, I added :
```
@ViewChildren(DynamicComponent) myDynamicComponent: DynamicComponent;

doStuff = () => {
    (this.myDynamicComponent.componentRef.instance as myContent).doStuff();
}
```
but I get : `Cannot read property 'instance' of undefined`

It looks like the selector doesn't find any DynamicComponent.

**However:**
I can select the item when I add a custom selector id : #myContent in the html, which solves the problem.

Thank you very much !
