### ISSUE TITLE
Support Angular 5

### ISSUE THREAD

**Issue by elclanrs** [gund/ng-dynamic-component#69]
I tried in Angular 5.0.0-rc.3 and I get an error the regarding the [OpaqueToken](https://angular.io/api/core/OpaqueToken) export which is deprecated.

According to https://github.com/angular/angular/issues/14427 you may just need replace [these](https://github.com/gund/ng-dynamic-component/search?utf8=%E2%9C%93&q=opaquetoken&type=) with `InjectionToken` instead.

**Comment by gund** [comment]
Yes, I will prepare an upgraded version very soon.

**Comment by gund** [comment]
Hey there!

Just published new next version of lib under `next` tag in NPM so you can go ahead and try it out:
```bash
$ npm install ng-dynamic-component@next
```

All changes are currently in separate `next` branch - until Angular 5 will be officially released.

**Comment by cankayacan** [comment]
https://github.com/cankayacan/ng5-dynamic-component-test

Getting this error: 

> Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.

**Comment by nlgi** [comment]
Hi!

There is another bug with official release of Angular 5.

`ERROR Error: Uncaught (in promise): Error: Unexpected value '[object Object]' imported by the module 'ImmeubleModule'. Please add a @NgModule annotation.`

Indeed in dynamic.module.d.ts:

`import { ComponentInjector } from './component-injector';
import { ModuleWithProviders, Type } from '@angular/core';
export declare class DynamicModule {
    static withComponents(components: Type<any>[], componentInjector?: Type<ComponentInjector>): ModuleWithProviders;
}
`

No @NgModule annotation.

Many thanks,

**Comment by gund** [comment]
Hey, you will not see any annotations in the `*.d.ts` files - those are just for typescript compiler not runtime.
I guess this problem happens because I build it with RC5 and you are trying with actual release v5.

I will publish stable version with v5 so you can try it

**Comment by Spanja** [comment]
Hello,

I still get the error message ERROR Error: Unexpected value '[object Object]' imported by the module 'MonthlyBonusModule'. Please add a @NgModule annotation.

Using ng5 - dynamic 2.0.1 & cli 1.5

**Comment by gund** [comment]
Hmm... I will try on a sample app later.
Thanks for reporting, reopening issue.

**Comment by lukaszbachman** [comment]
I ran into the same issue today using CLI 1.5, NG 2.1 and ng-dynamic-component 2.0.1, like all the others.
I compared the generated JS bundle for ng-dynamic-component and another open source library which is not triggering exceptions just to find that the generated class does contain additional metadata.

`
TooltipModule.decorators = [
        { type: NgModule, args: [{
                    imports: [CommonModule],
                    declarations: [TooltipDirective, TooltipContainerComponent],
                    exports: [TooltipDirective],
                    entryComponents: [TooltipContainerComponent]
                },] },
    ];
`

This `decorators` property is not present in case of generated `DynamicModule`, so I bet that this is what's causing NG to error out. I'm not sure though why this happens.

**Comment by gund** [comment]
@lukaszbachman thanks for pointing to this, I will check why they are not appearing

**Comment by gund** [comment]
Just confirmed that NGC does not generate metadata anymore for the project...
I guess it's because Angular v5 by default strips any angular specific decorators to optimize bundle.
Need to look for any config flags how to turn it off...

**Comment by gund** [comment]
So I found this property called [`generateCodeForLibraries`](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngtools_api2.ts#L49) for `angularCompilerOptions` in tsconfig.json and I tried to set it to true and still did not get any decorators emitted...

Really weird.
Anyone has any idea what might be the issue?

**Comment by elclanrs** [comment]
@gund, this seems to be related https://github.com/angular/angular/issues/20219

**Comment by gund** [comment]
@elclanrs looks interesting but they are talking about code-gen of `ngfactory`s and here we are not generating them.
In our case there are not a single decorator being emitted by the NGC.

I just tried to use TSC with the same config and it did output all decorators - so it's purely NGCs issue now.

Trying to build a reproduction app now...

**Comment by shlomiassaf** [comment]
very simple, use TS@2.4.2 not 2.5.3

The problem is angular not notifying about it

**Comment by shlomiassaf** [comment]
2.5.3 support can be tracked here angular/angular#20175

**Comment by gund** [comment]
Hey @shlomiassaf thanks for the info. Just tried with TS v2.4 and it did work.

Angular team already knows about the problem with decorators in TS v2.5 or it makes sense to create a repro app and link to the issue?

**Comment by shlomiassaf** [comment]
I don't know...
They know about it so work is on way... 

The issues are with tsickle mostly, not emitting the decorators... other then that you can AOT compile an app and it will work... 

Since it's one shot compile the data is kept

**Comment by gund** [comment]
You can try [v2.0.2](https://github.com/gund/ng-dynamic-component/releases/tag/v2.0.2) - should be fixed
