### ISSUE TITLE
Not able to build with AOT on Angular 5 and ndc 2.0.2

### ISSUE THREAD

**Issue by fijas** [gund/ng-dynamic-component#80]
Thanks for the work on resolving #69 . That seems to have solved the problem after updating to angular 5. But now when I try to build a production version of my app (with aot), I get the following error:

> ERROR in Error: Error encountered resolving symbol values statically. Calling function 'DynamicModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol DashModule in /var/www/genesis/client/src/app/dash/dash.module.ts, resolving symbol DashModule in /var/www/genesis/client/src/app/dash/dash.module.ts

This is the line the module file that causes the error:

> DynamicModule.withComponents([ DashletFavoriteComponent, DashletRecentComponent, DashletTrendingComponent ])

Am I missing something here?

"ng serve" works fine. So does "ng build" with aot false. Also the previous versions (angular 4 + ndc 1.x) used to work fine with aot enabled.

**Comment by gund** [comment]
Just a quick question, which version of Typescript are you using?
Because the version of it was a problem previously.

**Comment by fijas** [comment]
My typescript version is "2.4.2". Running the app through "ng serve" works well. The issue is only when I run "ng build" with the aot option enabled. With aot set as "false", ng build also works fine.

**Comment by lukaszbachman** [comment]
I can report the same issue here. Building with AOT faild, but regular builds are working fine. I'm also on TS 2.4.2.

**Comment by elclanrs** [comment]
I think I spoke too soon... Everything is fine during `ng serve`, but `ng build --prod` gives me the error.

**Comment by gund** [comment]
Hey! I just discovered that the path to typings file was wrong - so I published a new version and tried on test ng-cli project it compiled just fine in prod mode.

Also I additionally installed `tslib` as required by `peerDependencies` so maybe you will want to do that too.

Either of this 2 fixes the issue =)

**Comment by elclanrs** [comment]
@gund, it works great now. Thanks!
