### ISSUE TITLE
ngOnChanges called twice

### ISSUE THREAD

**Issue by jerousseau** [gund/ng-dynamic-component#88]
Hi,

When we change the component on the fly, the ngOnChanges of the new component is called twice, first time with the inputs we have passed to the new component ( firstChange: true and no previousValue) and a second time with in previousValue the value of the old component.
Any idea to avoid this ?

Thanks

Plnkr example to reproduce : https://plnkr.co/edit/uM7FzOmI4wNPE4F8WtFR

**Comment by gund** [comment]
Hi @jerousseau,

Sorry for late response. Just got my hands on your plunkr.

I can confirm that this is a bug.
I will build a test case for it and then fix it pretty soon.

Thanks for building awesome example.

**Comment by alandroid** [comment]
I am still experiencing this issue, perhaps only a change detection issue but not sure

**Comment by gund** [comment]
@alandroid can you please create a plunkr with repro?
