### ISSUE TITLE
Failed to compile: Can't resolve 'tslib'

### ISSUE THREAD

**Issue by hpawe01** [gund/ng-dynamic-component#9]
Hello,
your Package looks promising, but I cannot get it to work.
When I use this package with the current angular version (either 4.0.0 or 4.0.1), I get the following error message:

```
ERROR in ./~/ng-dynamic-component/dist/dynamic/custom-simple-change.js
Module not found: Error: Can't resolve 'tslib' in '/home/vagrant/component-test/node_modules/ng-dynamic-component/dist/dynamic'
 @ ./~/ng-dynamic-component/dist/dynamic/custom-simple-change.js 1:0-33
 @ ./~/ng-dynamic-component/dist/dynamic/dynamic.directive.js
 @ ./~/ng-dynamic-component/dist/dynamic/index.js
 @ ./~/ng-dynamic-component/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

Steps to reproduce using Angular CLI: 
1. `ng new component-test`
2. `cd component-test`
3. `npm install --save ng-dynamic-component`
4. In `src/app/app.module.ts` add import-statement (`import { DynamicModule } from 'ng-dynamic-component';`) and module in imports-array.
5. `ng serve`

Cheers

**Comment by richardsengers** [comment]
Same problem here

**Comment by gund** [comment]
Well you just need to install npm module `tslib` and add to your tsconfig file `importHelpers: true`

**Comment by hpawe01** [comment]
Thanks, that worked for me. I only needed to install `tslib`. 

Maybe you can add this package to the `peerDependencies` section in your `package.json` file? That way the user would be notified when installing the package.

**Comment by gund** [comment]
Yes, that is good point. Will add that to peers. Cheers =)
