### ISSUE TITLE
How to create new instance of dynamic component

### ISSUE THREAD

**Issue by sumitsijaria** [gund/ng-dynamic-component#94]
Hi,

It's great module to use for dynamic component rendering. However facing issues in data binding. Same instance of component being render in DOM. If I am trying to insert a type of component having values inserted from response object, same values are being binded previously added dynamic component.

Is there a way to create new instance of it and then add to the DOM.

Thanks in advance

**Comment by gund** [comment]
You mean you want to recreate an instance of the same component that is already rendered?

**Comment by sumitsijaria** [comment]
Yes creating a new instance inside list item based on some condition.

Though,I am able to implement it by creating dynamic components using component factory resolver so I have closed the issue.
