### ISSUE TITLE
Looping dynamic component changes order

### ISSUE THREAD

**Issue by vikrsing** [gund/ng-dynamic-component#96]
I am trying to loop like following code but the order of sections is not retained if same component type is used. Components with similar type all gets added at the end.

`<div data-paroller-factor="0.3" *ngFor="let section of sections; let i = index">
            <ndc-dynamic [ndcDynamicComponent]="section.component" [ndcDynamicInputs]="section.componentData"></ndc-dynamic>
        </div>`

**Comment by gund** [comment]
Maybe I do not understand correctly but it's up to you in what order you put sections to the `sections` variable (if it's of type array).

Would be better if you can create plunkr with example of the issue.

**Comment by gund** [comment]
Closning due to inactivity.
